---
- name: Restart postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted

- name: Restart rspamd
  ansible.builtin.systemd_service:
    name: rspamd
    state: restarted

- name: Restart dovecot
  ansible.builtin.systemd_service:
    name: dovecot
    state: restarted

- name: Compile dovecot sieve
  ansible.builtin.command:
    cmd: /usr/bin/sievec {{ sieve_file.dest }}
  when: sieve_file.changed
