---
- name: Install ClamAV
  ansible.builtin.package:
    name:
      - clamav
      - clamav-freshclam
      - clamd

- name: Install freshclam config file
  ansible.builtin.copy:
    dest: /etc/freshclam.conf
    src: ../templates/freshclam.conf
    mode: "0600"
    owner: root
    group: root
  notify:
    - Restart freshclam

- name: Install ClamAV config file
  ansible.builtin.copy:
    dest: /etc/clamd.d/scan.conf
    src: ../templates/scan.conf
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart clamd

- name: Enable and start ClamAV
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - clamd@scan
    - clamav-freshclam
