---
- name: Restart freshclam
  ansible.builtin.systemd_service:
    name: clamav-freshclam
    state: restarted

- name: Restart clamd
  ansible.builtin.systemd_service:
    name: clamd@scan
    state: restarted
